### ISSUE TITLE
dist.ini version and $VERSION do not match.

### ISSUE THREAD

**Issue by bokutin** [upasana-me/Plack-Middleware-RemoveRedundantBody#5]
https://github.com/upasana-me/Plack-Middleware-RemoveRedundantBody/blob/59a45edb0555064b96aedb994588fce1232d312e/dist.ini#L2

https://github.com/upasana-me/Plack-Middleware-RemoveRedundantBody/blob/59a45edb0555064b96aedb994588fce1232d312e/lib/Plack/Middleware/RemoveRedundantBody.pm#L7

**Comment by upasana-me** [comment]
Fixed with 0e375bfbb4e11fb3f7eaf39f8234d8581fb99d99 and already available on CPAN, thank you for reporting.
